@startuml
interface Product
class ConcreteProduct

interface Creator {
  FactoryMethod()
  AnOperation()
}
class ConcreteCreator {
  FactoryMethod()
}

ConcreteProduct -u-> Product
ConcreteCreator -u-> Creator
ConcreteCreator .l.> ConcreteProduct

note right of Creator::AnOperation
  product = FactoryMethod()
end note
note right of ConcreteCreator::FactoryMethod
  returns new ConcreteProduct()
end note
@enduml