@startuml
class System{
  do_job_A()
  do_job_B()
  do_job_C()
  change_state()
}

interface State{
  do_job_A()
  do_job_B()
  do_job_C()
}

class ConcreteStateA {
  do_job_A()
  do_job_B()
  do_job_C()
}
class ConcreteStateB {
  do_job_A()
  do_job_B()
  do_job_C()
}


ConcreteStateA -u-> State
ConcreteStateB -u-> State
System .l.> State

@enduml
